version: "3"

services:
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: "ng-frontend"
    restart: unless-stopped
    ports:
      - "8181:80"
    networks:
      - webnet
    depends_on:
      - backend

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: "nest-backend"
    restart: unless-stopped
    ports:
      - "8000:3000"
    networks:
      - webnet
    env_file: .env

networks:
  webnet:
    driver: bridge
